# render.yaml
services:
  - type: web
    name: DocConvert-bot
    env: python
    # ជំហាននេះដំឡើង FFmpeg និង Tesseract-OCR (សម្រាប់មុខងារ Media/OCR)
    buildCommand: apt-get update && apt-get install -y ffmpeg tesseract-ocr && pip install -r requirements.txt
    
    # ត្រូវប្រាកដថាឯកសារ Python មេរបស់អ្នកមានឈ្មោះថា 'main.py'
    # Gunicorn Start Command
    startCommand: gunicorn main:main -b 0.0.0.0:$PORT -k gevent --workers 1 --timeout 120
    
    plan: free 
    envVars:
      - key: BOT_TOKEN
        value: 8358054959:AAHj7HQZqEd94V20j8kvWkY6UCseXsz10-Q # ដាក់ Bot Token របស់អ្នក
